/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-surface-variant": "#4c4546",
        "surface-bright": "#f9f9f9",
        "inverse-surface": "#2f3131",
        "on-primary-container": "#848484",
        "surface-container-low": "#f3f3f4",
        "on-error-container": "#93000a",
        "on-secondary-container": "#64625f",
        "secondary-fixed-dim": "#c9c6c2",
        "on-primary-fixed": "#1b1b1b",
        "on-error": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "outline-variant": "#cfc4c5",
        "primary-fixed-dim": "#c6c6c6",
        "secondary-fixed": "#e5e2de",
        "on-primary-fixed-variant": "#474747",
        "on-secondary": "#ffffff",
        "surface": "#f9f9f9",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed-variant": "#474747",
        "primary-container": "#1b1b1b",
        "on-surface": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "surface-container": "#eeeeee",
        "on-tertiary-container": "#848484",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-tint": "#5e5e5e",
        "inverse-primary": "#c6c6c6",
        "secondary": "#5f5e5b",
        "primary-fixed": "#e2e2e2",
        "primary": "#000000",
        "tertiary-fixed-dim": "#c6c6c6",
        "border-default": "#000000",
        "error": "#ba1a1a",
        "surface-dim": "#dadada",
        "tertiary-container": "#1b1b1b",
        "on-secondary-fixed": "#1c1c19",
        "surface-variant": "#e2e2e2",
        "tertiary": "#000000",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#e2e2e2",
        "secondary-container": "#e2dfdb",
        "on-tertiary-fixed": "#1b1b1b",
        "outline": "#7e7576",
        "accent-green": "#16a34a",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#474744",
        "background": "#f9f9f9"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "8px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "margin-desktop": "40px",
        "border-width": "2px"
      },
      "fontFamily": {
        "body-sm": ["Barlow Condensed", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Libre Caslon Text", "serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Libre Caslon Text", "serif"],
        "body-md": ["Barlow Condensed", "sans-serif"],
        "headline-lg-mobile": ["Libre Caslon Text", "serif"]
      },
      "fontSize": {
        "body-sm": ["15px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "0em", "fontWeight": "700" }],
        "code-md": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["18px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
